# render.yaml
services:
  - type: web
    name: studybot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    pythonVersion: 3.10
    envVars:
      - key: TOKEN
        fromGroup: telegram-secrets

